### ISSUE TITLE
After pjax call infinite pagination call two times!

### ISSUE THREAD

**Issue by hardikamutech** [nirvana-msu/yii2-infinite-scroll#11]
After my pjax call. infinite pagination call two times and display double result. means 
for example http://mysite.com/frontend/web/site/index?page=2&per-page=2 call two times in console and render one page result two times. :( 
please help!
Here is my code!

``` html
<?php $pjax = Pjax::begin(); ?>
<div class="well pr_box">
    <?= Html::beginForm(['site/index'], 'post', ['data-pjax' => '', 'class' => 'form-horizontal']); ?>
    <h4>What's New</h4>

    <div class="form-group" style="padding:14px;">

        <?= Html::textarea('status_update', '', ['class' => 'form-control']) ?>
    </div>
    <ul class="list-inline">

        <li><a href=""> <i class="fa fa-picture-o"></i></a></li>

        <?= Html::submitButton('Submit', ['class' => 'btn btn-success right-side']) ?>
    </ul>

    <?= Html::endForm() ?>
</div>
<?php echo ListView::widget([
    'id' => 'my-listview-id',
    'layout' => "{summary}\n<div class=\"items\">{items}</div>\n{pager}",
    'options' => [
        'tag' => 'div',
    ],
    'dataProvider' => $listDataProvider,
    'itemView' => function ($model, $key, $index, $widget) {
        $itemContent = $this->render('_list_item', ['model' => $model]);
        /* Display an Advertisement after the first list item */
        return $itemContent;
        /* Or if you just want to display the list item only: */
    },
    'itemOptions' => [
        'tag' => false, 'class' => 'item',
    ],
    'summary' => '',

    /* do not display {summary} */
    // 'layout' => '{items}{pager}',
    'pager' => [
        'class' => InfiniteScrollPager::className(),
        'widgetId' => 'my-listview-id',
        'itemsCssClass' => 'items',
        //'pjaxContainer' => $pjax->id,
        //  'contentLoadedCallback' => 'afterAjaxListViewUpdate',
        'nextPageLabel' => 'Load more',
        // 'linkOptions' => [
        //     'class' => 'btn btn-lg btn-block text-center',
        // ],
        'pluginOptions' => [
            'loading' => [
                //'msgText' => "<p class='text-center'>Loading next set of items...</p>",
                'finishedMsg' => "<p class='text-center'>No more items to load</p>",
                //'img' => 'http://google.com',
            ],
            //  'behavior' => InfiniteScrollPager::BEHAVIOR_TWITTER,
        ],
    ],
]); ?>
<?php Pjax::end(); ?>`
```

**Comment by hardikamutech** [comment]
dose any one take care of this repository? please answer!

**Comment by nirvana-msu** [comment]
Please update your example to leave only relevant information, at the same time sufficient to reproduce the problem. There does not seem to be anything wrong with the code you provided. Note that `Pjax` is completely irrelevant here, it is never invoked. If you're using automatic scrolling (default behaviour), there isn't even any link that could trigger `Pjax`. If you're using manual (Twitter) behavior, then `preventDefault()` is invoked when handling link click in `manual-trigger.js`. This extension is just a very thin wrapper around infinite-scroll jQuery plugin, so I would suggest placing some breakpoints inside the plugin code itself to see why it is being called twice in your case. There must be some other part of your application that is causing the problem.

If there is an external link (outside `ListView`) that causes your `Pjax` to reload the whole content, including `ListView` itself, it should cause the old plugin instance to stop working (since the DOM element it was linked to no longer exists) and register a new one instead. If that doesn't happen for whatever reason, you can always destroy the old plugin instance yourself after `Pjax` completes.

**Comment by hardikamutech** [comment]
Thanks for the answer. But I have switched to different library as haven't heard from you since long. I still appreciate your response. 

Thanks Again!
